[[constraint]]
  branch = "master"
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[prune]
  go-tests = true

[[constraint]]
  name = "github.com/mitchellh/gox"
  version = "0.4.0"
